config/routes.rb
Rails.application.routes.draw do
  resources :cookbooks
  resources :recipes
  resources :ingredients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "cookbooks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cookbook.rb
# frozen_string_literal: true

class Cookbook < ApplicationRecord
  has_many :cookbook_recipes
  has_many :recipes, through: :cookbook_recipes

  after_create_commit { broadcast_prepend_to "cookbooks" }
  after_update_commit { broadcast_replace_to "cookbooks" }
  after_destroy_commit { broadcast_remove_to "cookbooks" }

  validates :name, presence: true, uniqueness: true
end

app/models/cookbook_recipe.rb
# frozen_string_literal: true

class CookbookRecipe < ApplicationRecord
  belongs_to :cookbook
  belongs_to :recipe
end

app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
  belongs_to :ingredient_type

  validates :name, presence: true, uniqueness: true
end

app/models/ingredient_type.rb
class IngredientType < ApplicationRecord
  has_many :ingredients
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  has_many :cookbook_recipes
  has_many :cookbooks, through: :cookbook_recipes

  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  has_many :recipe_steps

  validates :name, presence: true, uniqueness: true
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/recipe_step.rb
class RecipeStep < ApplicationRecord
  belongs_to :recipe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cookbooks_controller.rb
class CookbooksController < ApplicationController
  before_action :set_cookbook, only: %i[ show edit update destroy ]

  def index
    @cookbooks = Cookbook.all.order(name: :asc)
  end

  def show
  end

  def new
    @cookbook = Cookbook.new
  end

  def edit
  end

  def create
    @cookbook = Cookbook.new(cookbook_params)

    respond_to do |format|
      if @cookbook.save
        format.turbo_stream
        format.html { redirect_to cookbook_url(@cookbook), notice: "Cookbook was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cookbook.update(cookbook_params)
        format.html { redirect_to cookbook_url(@cookbook), notice: "Cookbook was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cookbook.destroy

    respond_to do |format|
      format.html { redirect_to cookbooks_url, notice: "Cookbook was successfully destroyed." }
    end
  end

  private
    def set_cookbook
      @cookbook = Cookbook.find(params[:id])
    end

    def cookbook_params
      params.require(:cookbook).permit(:name, :description)
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: %i[ show edit update destroy ]

  def index
    @ingredients = Ingredient.all
  end

  def show
  end

  def new
    @ingredient = Ingredient.new
  end

  def edit
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to ingredient_url(@ingredient), notice: "Ingredient was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to ingredient_url(@ingredient), notice: "Ingredient was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: "Ingredient was successfully destroyed." }
    end
  end

  private
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    def ingredient_params
      params.require(:ingredient).permit(:name, :available, :calories)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]

  def index
    @recipes = Recipe.all
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def edit
  end

  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
    end
  end

  private
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cookbooks_helper.rb
module CookbooksHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/cookbooks/_cookbook.html.erb
<%= turbo_frame_tag cookbook do %>
  <div>
    <h1 class="my-5 font-bold text-xl">
      <%= cookbook.name %>
    </h1>

    <p class="my-5">
      <%= cookbook.description || "No description yet" %>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1">Recipes: (<%= cookbook.recipes.count %>)</strong>
      <%- cookbook.recipes.each do |recipe| %>
        <a href="<%= recipe_path(recipe) %>" class="hover:font-bold"><%= recipe.name %></a>
      <% end %>
    </p>

    <% if action_name != "show" %>
      <%= link_to "Show this cookbook", cookbook, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= link_to 'Edit this cookbook', edit_cookbook_path(cookbook), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
      <%= button_to 'Delete this cookbook', cookbook_path(cookbook), method: :delete, class: "rounded-lg py-3 ml-2 px-5 bg-red-100 inline-block font-medium" %>

      <hr class="mt-6">
    <% end %>
  </div>
<% end %>

app/views/cookbooks/_form.html.erb
<%= form_with(model: cookbook, id: "#{dom_id(cookbook)}_form") do |form| %>
  <%= render "shared/form_errors", model: cookbook %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/cookbooks/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing cookbook</h1>

  <%= render "form", cookbook: @cookbook %>

  <%= link_to "Show this cookbook", @cookbook, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to cookbooks", cookbooks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/cookbooks/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Cookbooks</h1>
    <%= turbo_frame_tag dom_id(Cookbook.new) do %>
      <%= link_to 'New cookbook', new_cookbook_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <% end %>
  </div>

  <div class="min-w-full">
    <%= turbo_stream_from "cookbooks" %>
    <%= turbo_frame_tag "cookbooks" do %>
      <%= render @cookbooks %>
    <% end %>
  </div>
</div>

app/views/cookbooks/new.html.erb
<%= turbo_frame_tag dom_id(@cookbook) do %>
  <div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-4xl">New cookbook</h1>

    <%= render "form", cookbook: @cookbook %>

    <%= link_to 'Back to cookbooks', cookbooks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
<% end %>

app/views/cookbooks/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @cookbook %>

    <%= link_to 'Edit this cookbook', edit_cookbook_path(@cookbook), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this cookbook', cookbook_path(@cookbook), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to cookbooks', cookbooks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, class: "contents") do |form| %>
  <%= render "shared/form_errors", model: ingredient %>

  <div class="inline-table">
    <div class="table-cell pr-4">
      <%= form.label :name, class: "table-row" %>
      <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="table-cell pr-4">
      <%= form.label :quantity %>
      <%= form.text_field :quantity, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="table-cell pr-4">
      <%= form.label :calories %>
      <%= form.number_field :calories, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="table-cell align-bottom">
      <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    </div>
  </div>

<% end %>

app/views/ingredients/_ingredient.html.erb
<div id="<%= dom_id ingredient %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= ingredient.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Quantity:</strong>
    <%= ingredient.available %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Calories:</strong>
    <%= ingredient.calories %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this ingredient", ingredient, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this ingredient', edit_ingredient_path(ingredient), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/ingredients/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing ingredient</h1>

  <%= render "form", ingredient: @ingredient %>

  <%= link_to "Show this ingredient", @ingredient, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to ingredients", ingredients_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/ingredients/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Ingredients</h1>
    <%= link_to 'New ingredient', new_ingredient_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="ingredients" class="min-w-full">
    <%= render @ingredients %>
  </div>
</div>

app/views/ingredients/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New ingredient</h1>

  <%= render "form", ingredient: @ingredient %>

  <%= link_to 'Back to ingredients', ingredients_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/ingredients/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @ingredient %>

    <%= link_to 'Edit this ingredient', edit_ingredient_path(@ingredient), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this ingredient', ingredient_path(@ingredient), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to ingredients', ingredients_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CookbookRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= link_to  "Cookbooks", cookbooks_path %>
      <%= link_to  "Recipes", recipes_path %>
      <%= link_to  "Ingredients", ingredients_path %>
    </header>
    <main class="container mx-auto mt-28 px-5 flex">
      
      <%= yield %>
    </main>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, class: "contents") do |form| %>
  <%= render "shared/form_errors", model: recipe %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <strong>Ingredients</strong>
    <%= render "ingredients/form", ingredient: @recipe.ingredients.build %>
    <%= render recipe.ingredients %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= recipe.name %>
  </p>

  <div class="flex flex-row">
    <div class="basis-1/4">
      <h2 class="text-xl font-bold mb-4">Ingredients</h2>
        <%- recipe.ingredients.each do |ingredient| %>
          <div class="flex flex-row">
            <span class="basis-1/2"><%= number_to_human(ingredient.recipe_ingredients.first.quantity, units: { unit: "g" }) %>
            <span class="basis-1/2"><%= ingredient.name %></span>
          </div>
        <% end %>
    </div>

    <div class="basis-3/4">
      <h2 class="text-xl font-bold mb-4">Steps</h2>
      <%- recipe.recipe_steps.each do |step| %>
        <p><%= step.description %></p>
      <% end %>
    </div>
  </div>


  <% if action_name != "show" %>
    <%= link_to "Show this recipe", recipe, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this recipe', edit_recipe_path(recipe), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/recipes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing recipe</h1>

  <%= render "form", recipe: @recipe %>

  <%= link_to "Show this recipe", @recipe, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to recipes", recipes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/recipes/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Recipes</h1>
    <%= link_to 'New recipe', new_recipe_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="recipes" class="min-w-full">
    <%- @recipes.each do |recipe| %>
    <div class="mt-10 p-5 border-s-2 hover:cursor-pointer hover:bg-sky-200">
        <a href="<%= recipe_path(recipe) %>" >
          <h2 class="text-2xl font-bold"><%= recipe.name %></h2>
          <p><%= recipe.blurb %></p>
        </a>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New recipe</h1>

  <%= render "form", recipe: @recipe %>

  <%= link_to 'Back to recipes', recipes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/recipes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @recipe %>

    <%= link_to 'Edit this recipe', edit_recipe_path(@recipe), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this recipe', recipe_path(@recipe), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to recipes', recipes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/shared/_form_errors.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
    <h2><%= pluralize(model.errors.count, "error") %> prohibited this <%= model.class.name %> from being saved:</h2>

    <ul>
      <% model.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>